### ISSUE TITLE
Text as intersectPath

### ISSUE THREAD

**Issue by Timvdv** [williamngan/pt#1]
Hello!

Not sure if this is the right place to ask, but I'm wondering if there is a way to use text as a mask in pt.js.

I'm trying to combine the font.js and the samplepoints demo so that the dots transform into the text.

![schermafbeelding 2015-09-29 om 20 44 18](https://cloud.githubusercontent.com/assets/979227/10174603/f115f37c-66ea-11e5-999c-f7515645abbc.png)

Awesome library by the way!

**Comment by williamngan** [comment]
Hi Timvdv, I believe this is possible via one of canvas context's [globalCompositeOperation](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation). For example,
`space.ctx.globalCompositeOperation = "source-over"`

See "Zebra Reflection Effect" here for a similar effect:
http://www.html5rocks.com/en/tutorials/canvas/texteffects/#toc-text-shadows

Give it a try! :+1:

**Comment by Timvdv** [comment]
It worked thanks :smile: Thanks for the tip!

Actually used: `context.globalCompositeOperation = 'source-atop';`

![schermafbeelding 2015-10-01 om 14 46 22](https://cloud.githubusercontent.com/assets/979227/10220955/54aaee0e-684b-11e5-8718-2f4ffb9568a0.png)

**Comment by williamngan** [comment]
Nice work!

And I'll try to make blending mode easier to access in Pt in the next release. Thanks Tim.
