### ISSUE TITLE
grid.canFit doesn't work on empty grid

### ISSUE THREAD

**Issue by tofuness** [williamngan/pt#14]
Following code doesn't work.
```javascript
var grid = new Grid([0, 0]).to([50, 50]).init(5, 5);
console.log(grid.canFit(0, 0, 1, 1));
```
Gives us `Uncaught TypeError: Cannot read property '0' of undefined` on this line:
https://github.com/williamngan/pt/blob/fe74d2a91affec3c549a32990f49797f429349a4/src/coffee/core/Grid.coffee#L179

**Comment by williamngan** [comment]
Thanks for reporting. Will fix!

**Comment by williamngan** [comment]
Fixed in  https://github.com/williamngan/pt/commit/c1bf75185185776946582bf50eee091c1950c2db

Looks like the layout property wasn't initiated. Good catch.

Pt 0.2.0 just released too. Take a look :)
http://williamngan.github.io/pt/docs/guide/migration.html

**Comment by tofuness** [comment]
Thank you for fixing this, @williamngan. Great work on 0.2.0!
