### ISSUE TITLE
collideCircle2D?

### ISSUE THREAD

**Issue by adekbadek** [williamngan/pt#2]
I'm trying to collide particles with a circle, but there is no explicit method for that. I was thinking about making a new particle for the circle, but I'd have to override it's being a particle (no movement, mass, etc.).

**Comment by williamngan** [comment]
Hi adekbadek, Particle is a kind of Circle so you can use all the circle methods in Particle. 

Take a look at:
http://williamngan.github.io/pt/docs/#inherited-Particle

And a collision example:
https://github.com/williamngan/pt/blob/master/demo/particle.collideLine2d.js
