### ISSUE TITLE
Do you have any guide for angular 5 ?

### ISSUE THREAD

**Issue by gtzinos** [williamngan/pt#33]

**Comment by williamngan** [comment]
Hi @gtzinos, there's an improved version of Pt called "Pts", written in typescript and better support for npm workflow. Please take a look at [https://ptsjs.org](https://ptsjs.org).

We don't have Angular guide yet, but there's a [getting-started guide](http://ptsjs.org/guide/get-started-0100) as well as a [React example repo](https://github.com/williamngan/pts-react-example). Angular workflow should be fairly straighforward. If you encounter a problem, please find an issue in the Pts repo. Thanks!

**Comment by gtzinos** [comment]
Sorry i forgot to close the issue, i had already implement it by npm. Thank you for your great work!
