### ISSUE TITLE
Support for higher pixel density

### ISSUE THREAD

**Issue by tofuness** [williamngan/pt#4]
Canvas drawings become blurry on screens with higher `window.devicePixelRatio`.

My current quick hack is just to use the css `transform: scale`. Not pretty :disappointed_relieved:

**Comment by williamngan** [comment]
Yep, it's a problem. Looks like we would need to implement something insane to check pixel ratio, like this one: 
http://www.html5rocks.com/en/tutorials/canvas/hidpi/

Or are there a more elegant solution?

**Comment by tofuness** [comment]
Looked around a bit and it seems like a lot of people have solved the problem like that (`ctx.scale()`).
Not sure how easy this is to implement though in a library like Pt.

**Comment by williamngan** [comment]
@tofuness I pushed a fix today. Pt now supports retina automatically, and you can turn it off by the `devicePixelSupport` parameter in CanvasSpace's [display](http://williamngan.github.io/pt/docs/#func-CanvasSpace-display) function.

And Pt now supports multi-touch as well! See Space's [bindTouch](http://williamngan.github.io/pt/docs/#func-Space-bindTouch) and add a `onTouchAction` handler to your items in space.

Here's a quick test demo (try it in mobile): http://williamngan.github.io/pt/demo/mobileapp.html

Give it a try and let me know if you find any issues. Cheers!

**Comment by tofuness** [comment]
Tried it out and it LGTM. I'll let you know if I run into any new problems. :ok_hand:
